CREATE TABLE [dbo].[Contacts]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[GenreId] INT NULL,
	[Nom] NVARCHAR(100) NOT NULL,
	[Prenom] NVARCHAR(100) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
	[Tel] NVARCHAR(100) NULL,
	[Sujet] NVARCHAR(100) NOT NULL,
	[Message] TEXT,
	[CreatedAt] DATETIME2(0) NOT NULL DEFAULT GETDATE(),
	[AnsweredAt] DATETIME2(0) NULL,

	FOREIGN KEY ([GenreId]) REFERENCES Genres([Id]) ON DELETE SET NULL
)
