CREATE TABLE [dbo].[Produits]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Slug] NVARCHAR(100) NOT NULL UNIQUE,
	[Titre] NVARCHAR(80) NOT NULL,
	[Description] TEXT NULL,
	[EnAffiche] BIT NOT NULL DEFAULT 0,
	[CreatedAt] DATETIME2(0) NOT NULL DEFAULT GETDATE(),
	[UpdatedAt] DATETIME2(0) NULL

)
